const data=[
    {
        key:1,
        img:"https://m.media-amazon.com/images/I/71cflgAolqL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"700",
        brand:"PUMA"
    },
    {
        key:2,
        img:"https://m.media-amazon.com/images/I/71lFYVmnDEL._SY625_.jpg",
        name:" Ruben Sneaker",
        price:"250",
        brand:"ADIDAS"
    },
    {
        key:3,
        img:"https://m.media-amazon.com/images/I/71s4yJYxVjL._SY625_.jpg",
        name:"Casual Sneaker Shoes ",
        price:"2240",
        brand:"NIKE"
    },
    {
        key:4,
        img:"https://m.media-amazon.com/images/I/61caYFuVm3L._SY625_.jpg",
        name:" Sneaker Shoes",
        price:"1700",
        brand:"CROCS"
    },
    {
        key:5,
        img:"https://m.media-amazon.com/images/I/61pkeQ763GL._SY625_.jpg",
        name:"Running Shoes",
        price:"700",
        brand:"CAMPUS"
    },
    {
        key:6,
        img:"https://m.media-amazon.com/images/I/41TtO1wkUhL._SY625_.jpg",
        name:" Casual Sneakers",
        price:"1500",
        brand:"PUMA"
    },
    {
        key:7,
        img:"https://m.media-amazon.com/images/I/51SdxYHSWkL._SX625_.jpg",
        name:"Sneakers for Men",
        price:"1899",
        brand:"ADIDAS"
    },
    {
        key:8,
        img:"https://m.media-amazon.com/images/I/61KpHOx79FL._SY625_.jpg",
        name:"Comport Sneakers",
        price:"799",
        brand:"NIKE"
    },
    {
        key:9,
        img:"https://m.media-amazon.com/images/I/61UEBoJGmLL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"1599",
        brand:"CROCS"
    },
    
    {
        key:10,
        img:"https://m.media-amazon.com/images/I/61Z9LJIYepL._SY625_.jpg",
        name:"Men's Sneaker",
        price:"1900",
        brand:"CAMPUS"
    },
    {
        key:11,
        img:"https://m.media-amazon.com/images/I/71m+EGqdJ0L._SY625_.jpg",
        name:"Sneaker",
        price:"1800",
        brand:"PUMA"
    },
    {
        key:12,
        img:"https://m.media-amazon.com/images/I/71dGrejh08L._SY625_.jpg",
        name:"",
        price:"600",
        brand:"ADIDAS"
    },
    {
        key:13,
        img:"https://m.media-amazon.com/images/I/71k2RaCoofL._SY625_.jpg",
        name:" Casual Sneaker ",
        price:"700",
        brand:"NIKE"
    },
    {
        key:14,
        img:"https://m.media-amazon.com/images/I/41Mvp90ah9L._SY695_.jpg",
        name:"Sneakers",
        price:"999",
        brand:"CAMPUS"
    },
    {
        key:15,
        img:"https://m.media-amazon.com/images/I/71xWtLhH2GL._SX625_.jpg",
        name:"Casual Shoe",
        price:"799",
        brand:"CROCS"
    },
    {
        key:16,
        img:"https://m.media-amazon.com/images/I/81mw0IfvWIL._SX625_.jpg",
        name:"Mens Bumper Sneaker",
        price:"799",
        brand:"PUMA"
    },
    {
        key:17,
        img:"https://m.media-amazon.com/images/I/61bKBEBbUAL._SY695_.jpg",
        name:"Casual Sneaker Shoes ",
        price:"700",
        brand:"ADIDAS"
    },
    {
        key:18,
        img:"https://m.media-amazon.com/images/I/61zeYGiaZGL._SY625_.jpg",
        name:"Sole Sneakers",
        price:"800",
        brand:"NIKE"
    },
    {
        key:19,
        img:"https://m.media-amazon.com/images/I/41zOY8G0Q0L._SY395_SX395_.jpg",
        name:" Casual Sneaker Shoes ",
        price:"1199",
        brand:"CAMPUS"
    },
    {
        key:20,
        img:"https://m.media-amazon.com/images/I/31+g1YMUO8L.jpg",
        name:"Casual Sneaker Shoes",
        price:"400",
        brand:"CROCS"
    },
    {
        key:21,
        img:"https://m.media-amazon.com/images/I/713G8fax-4L._SY625_.jpg",
        name:"Casual Shoe",
        price:"1700",
        brand:"PUMA"
    },
    {
        key:22,
        img:"https://m.media-amazon.com/images/I/61qXdWV980L._SY625_.jpg",
        name:"Sneakers",
        price:"1600",
        brand:"ADIDAS"
    },
    {
        key:23,
        img:"https://m.media-amazon.com/images/I/61tSWiTp+tL._SY625_.jpg",
        name:"",
        price:"800",
        brand:"NIKE"
    },
    {
        key:24,
        img:"https://m.media-amazon.com/images/I/71gVtJPjZZL._SX625_.jpg",
        name:"",
        price:"1400",
        brand:"CAMPUS"
    },
    {
        key:25,
        img:"https://m.media-amazon.com/images/I/61CS689WOiL._SY625_.jpg",
        name:"Sneaker Shoes for Men",
        price:"1888",
        brand:"PUMA"
    },
    {
        key:26,
        img:"https://m.media-amazon.com/images/I/71uiQMMydGL._SY625_.jpg",
        name:"Sneaker",
        price:"2160",
        brand:"ADIDAS"
    },
    {
        key:27,
        img:"https://m.media-amazon.com/images/I/71m+EGqdJ0L._SY625_.jpg",
        name:"Sneaker",
        price:"1800",
        brand:"ADIDAS"
    },
    {
        key:28,
        img:"https://m.media-amazon.com/images/I/61YIGF+3skL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"1668",
        brand:"NIKE"
    },
    {
        key:29,
        img:"https://m.media-amazon.com/images/I/71s4yJYxVjL._SY625_.jpg",
        name:"Casual Sneaker Shoes ",
        price:"2240",
        brand:"CROCS"
    },
    {
        key:30,
        img:"https://m.media-amazon.com/images/I/71yCzc9dGrL._SY625_.jpg",
        name:" Sneaker",
        price:"1900",
        brand:"CAMPUS"
    },
    {
        key:31,
        img:"https://m.media-amazon.com/images/I/61Z9LJIYepL._SY625_.jpg",
        name:"Men's Sneaker",
        price:"1900",
        brand:"PUMA"
    },
    {
        key:32,
        img:"https://m.media-amazon.com/images/I/414FfrsToBL._SY695_.jpg",
        name:"Sneaker",
        price:"1900",
        brand:"ADIDAS"
    },
    {
        key:33,
        img:"https://m.media-amazon.com/images/I/514BET30sxL._SY695_.jpg",
        name:"Sneakers",
        price:"756",
        brand:"NIKE"
    },
    {
        key:34,
        img:"https://m.media-amazon.com/images/I/71SYWNzpuSL._SX625_.jpg",
        name:"Casual Shoe",
        price:"769",
        brand:"CAMPUS"
    },
    {
        key:35,
        img:"https://m.media-amazon.com/images/I/61UEBoJGmLL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"1599",
        brand:"PUMA"
    },
    {
        key:36,
        img:"https://m.media-amazon.com/images/I/51SdxYHSWkL._SX625_.jpg",
        name:"Sneakers for Men",
        price:"1899",
        brand:"NIKE"
    },
    {
        key:37,
        img:"https://m.media-amazon.com/images/I/41TtO1wkUhL._SY625_.jpg",
        name:" Casual Sneakers",
        price:"1500",
        brand:"ADIDAS"
    },
    {
        key:38,
        img:"https://m.media-amazon.com/images/I/71y+d4hUVyL._SX625_.jpg",
        name:"Sneaker",
        price:"1602",
        brand:"CAMPUS"
    },
    {
        key:39,
        img:"https://m.media-amazon.com/images/I/71u78BeE5TL._SX625_.jpg",
        name:"Sneakers",
        price:"849",
        brand:"PUMA"
    },
    {
        key:40,
        img:"https://m.media-amazon.com/images/I/71lFYVmnDEL._SY625_.jpg",
        name:" Ruben Sneaker",
        price:"250",
        brand:"NIKE"
    },
    {
        key:41,
        img:"https://m.media-amazon.com/images/I/61wE1PW++7L._SX625_.jpg",
        name:"Sneaker",
        price:"764",
        brand:"CROCS"
    },
    {
        key:42,
        img:"https://m.media-amazon.com/images/I/514BET30sxL._SY695_.jpg",
        name:"Sneakers",
        price:"756",
        brand:"CAMPUS"
    },
    {
        key:43,
        img:"https://m.media-amazon.com/images/I/81mw0IfvWIL._SX625_.jpg",
        name:"",
        price:"799",
        brand:"ADIDAS"
    },
    {
        key:44,
        img:"https://m.media-amazon.com/images/I/61utX8kBDlL._SY625_.jpg",
        name:"Sports Running Shoes…",
        price:"6000",
        brand:"NIKE"
    },
    {
        key:45,
        img:"https://m.media-amazon.com/images/I/61tSWiTp+tL._SY625_.jpg",
        name:"",
        price:"800",
        brand:"CAMPUS"
    },
    {
        key:46,
        img:"https://m.media-amazon.com/images/I/71gVtJPjZZL._SX625_.jpg",
        name:"",
        price:"1400",
        brand:"PUMA"
    },
    {
        key:47,
        img:"https://m.media-amazon.com/images/I/61zeYGiaZGL._SY625_.jpg",
        name:"Sole Sneakers",
        price:"800",
        brand:"CAMPUS"
    },
    {
        key:48,
        img:"https://m.media-amazon.com/images/I/71cflgAolqL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"700",
        brand:"ADIDAS"
    },
    {
        key:49,
        img:"https://m.media-amazon.com/images/I/71m+EGqdJ0L._SY625_.jpg",
        name:"Sneaker",
        price:"1800",
        brand:"NIKE"
    },
    {
        key:50,
        img:"https://m.media-amazon.com/images/I/61qXdWV980L._SY625_.jpg",
        name:"Sneakers",
        price:"1600",
        brand:"NIKE"
    },
    {
        key:51,
        img:"https://m.media-amazon.com/images/I/41Mvp90ah9L._SY695_.jpg",
        name:"Sneakers",
        price:"999",
        brand:"PUMA"
    },
    {
        key:52,
        img:"https://m.media-amazon.com/images/I/71k2RaCoofL._SY625_.jpg",
        name:" Casual Sneaker ",
        price:"700",
        brand:"CAMPUS"
    },
    {
        key:53,
        img:"https://m.media-amazon.com/images/I/61KpHOx79FL._SY625_.jpg",
        name:"Comport Sneakers",
        price:"799",
        brand:"CROCS"
    },
    {
        key:54,
        img:"https://m.media-amazon.com/images/I/61CS689WOiL._SY625_.jpg",
        name:"Sneaker Shoes for Men",
        price:"1888",
        brand:"ADIDAS"
    },
    {
        key:55,
        img:"https://m.media-amazon.com/images/I/71uiQMMydGL._SY625_.jpg",
        name:"Sneaker",
        price:"2160",
        brand:"NIKE"
    },
    {
        key:56,
        img:"https://m.media-amazon.com/images/I/61Z9LJIYepL._SY625_.jpg",
        name:"Men's Sneaker",
        price:"1900",
        brand:"ADIDAS"
    },
    {
        key:57,
        img:"https://m.media-amazon.com/images/I/61UEBoJGmLL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"1599",
        brand:"ADIDAS"
    },
    {
        key:58,
        img:"https://m.media-amazon.com/images/I/71yCzc9dGrL._SY625_.jpg",
        name:" Sneaker",
        price:"1900",
        brand:"NIKE"
    },
    {
        key:59,
        img:"https://m.media-amazon.com/images/I/61YIGF+3skL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"1668",
        brand:"CAMPUS"
    },
    {
        key:60,
        img:"https://m.media-amazon.com/images/I/414FfrsToBL._SY695_.jpg",
        name:"Sneaker",
        price:"1900",
        brand:"CROCS"
    },
    {
        key:61,
        img:"https://m.media-amazon.com/images/I/71xWtLhH2GL._SX625_.jpg",
        name:"Casual Shoe",
        price:"799",
        brand:"PUMA"
    },
    {
        key:62,
        img:"https://m.media-amazon.com/images/I/71SYWNzpuSL._SX625_.jpg",
        name:"Casual Shoe",
        price:"769",
        brand:"CROCS"
    },
    {
        key:63,
        img:"https://m.media-amazon.com/images/I/81mw0IfvWIL._SX625_.jpg",
        name:"",
        price:"799",
        brand:"NIKE"
    },
    {
        key:64,
        img:"https://m.media-amazon.com/images/I/71s4yJYxVjL._SY625_.jpg",
        name:"Casual Sneaker Shoes ",
        price:"2240",
        brand:"CAMPUS"
    },
    {
        key:65,
        img:"https://m.media-amazon.com/images/I/61zeYGiaZGL._SY625_.jpg",
        name:"Sole Sneakers",
        price:"800",
        brand:"CROCS"
    },
    {
        key:66,
        img:"https://m.media-amazon.com/images/I/61utX8kBDlL._SY625_.jpg",
        name:"Sports Running Shoes…",
        price:"6000",
        brand:"PUMA"
    },
    {
        key:67,
        img:"https://m.media-amazon.com/images/I/81mw0IfvWIL._SX625_.jpg",
        name:"Mens Bumper Sneaker",
        price:"799",
        brand:"ADIDAS"
    },
    {
        key:68,
        img:"https://m.media-amazon.com/images/I/41Mvp90ah9L._SY695_.jpg",
        name:"Sneakers",
        price:"999",
        brand:"ADIDAS"
    },
    {
        key:69,
        img:"https://m.media-amazon.com/images/I/71k2RaCoofL._SY625_.jpg",
        name:" Casual Sneaker ",
        price:"700",
        brand:"CROCS"
    },
    {
        key:70,
        img:"https://m.media-amazon.com/images/I/71gVtJPjZZL._SX625_.jpg",
        name:"",
        price:"1400",
        brand:"NIKE"
    },
    {
        key:71,
        img:"https://m.media-amazon.com/images/I/71lFYVmnDEL._SY625_.jpg",
        name:" Ruben Sneaker",
        price:"250",
        brand:"CAMPUS"
    },
    {
        key:72,
        img:"https://m.media-amazon.com/images/I/31+g1YMUO8L.jpg",
        name:"Casual Sneaker Shoes",
        price:"400",
        brand:"CAMPUS"
    },
    {
        key:73,
        img:"https://m.media-amazon.com/images/I/61bKBEBbUAL._SY695_.jpg",
        name:"Casual Sneaker Shoes ",
        price:"700",
        brand:"NIKE"
    },
    {
        key:74,
        img:"https://m.media-amazon.com/images/I/71u78BeE5TL._SX625_.jpg",
        name:"Sneakers",
        price:"849",
        brand:"ADIDAS"
    },
    {
        key:75,
        img:"https://m.media-amazon.com/images/I/51SdxYHSWkL._SX625_.jpg",
        name:"Sneakers for Men",
        price:"1899",
        brand:"CROCS"
    },
    {
        key:76,
        img:"https://m.media-amazon.com/images/I/71SYWNzpuSL._SX625_.jpg",
        name:"Casual Shoe",
        price:"769",
        brand:"PUMA"
    },
    {
        key:77,
        img:"https://m.media-amazon.com/images/I/41TtO1wkUhL._SY625_.jpg",
        name:" Casual Sneakers",
        price:"1500",
        brand:"NIKE"
    },
    {
        key:78,
        img:"https://m.media-amazon.com/images/I/514BET30sxL._SY695_.jpg",
        name:"Sneakers",
        price:"756",
        brand:"CROCS"
    },
    {
        key:79,
        img:"https://m.media-amazon.com/images/I/414FfrsToBL._SY695_.jpg",
        name:"Sneaker",
        price:"1900",
        brand:"NIKE"
    },
    {
        key:80,
        img:"https://m.media-amazon.com/images/I/61Z9LJIYepL._SY625_.jpg",
        name:"Men's Sneaker",
        price:"1900",
        brand:"NIKE"
    },
    {
        key:81,
        img:"https://m.media-amazon.com/images/I/61tSWiTp+tL._SY625_.jpg",
        name:"",
        price:"800",
        brand:"CROCS"
    },
    {
        key:82,
        img:"https://m.media-amazon.com/images/I/61KpHOx79FL._SY625_.jpg",
        name:"Comport Sneakers",
        price:"799",
        brand:"CAMPUS"
    },
    {
        key:83,
        img:"https://m.media-amazon.com/images/I/71cflgAolqL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"700",
        brand:"NIKE"
    },
    {
        key:84,
        img:"https://m.media-amazon.com/images/I/61UEBoJGmLL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"1599",
        brand:"NIKE"
    },
    {
        key:85,
        img:"https://m.media-amazon.com/images/I/71yCzc9dGrL._SY625_.jpg",
        name:" Sneaker",
        price:"1900",
        brand:"PUMA"
    },
    {
        key:86,
        img:"https://m.media-amazon.com/images/I/61YIGF+3skL._SY625_.jpg",
        name:"Casual Sneaker Shoes",
        price:"1668",
        brand:"CROCS"
    },
    {
        key:87,
        img:"https://m.media-amazon.com/images/I/81mw0IfvWIL._SX625_.jpg",
        name:"",
        price:"799",
        brand:"CAMPUS"
    },
    {
        key:88,
        img:"https://m.media-amazon.com/images/I/71uiQMMydGL._SY625_.jpg",
        name:"Sneaker",
        price:"2160",
        brand:"CROCS"
    },
    {
        key:89,
        img:"https://m.media-amazon.com/images/I/61CS689WOiL._SY625_.jpg",
        name:"Sneaker Shoes for Men",
        price:"1888",
        brand:"NIKE"
    },
    {
        key:90,
        img:"https://m.media-amazon.com/images/I/71gVtJPjZZL._SX625_.jpg",
        name:"",
        price:"1400",
        brand:"ADIDAS"
    },
    {
        key:91,
        img:"https://m.media-amazon.com/images/I/61qXdWV980L._SY625_.jpg",
        name:"Sneakers",
        price:"1600",
        brand:"CAMPUS"
    },
    {
        key:92,
        img:"https://m.media-amazon.com/images/I/61zeYGiaZGL._SY625_.jpg",
        name:"Sole Sneakers",
        price:"800",
        brand:"PUMA"
    },
    {
        key:93,
        img:"https://m.media-amazon.com/images/I/71m+EGqdJ0L._SY625_.jpg",
        name:"Sneaker",
        price:"1800",
        brand:"CAMPUS"
    },
    {
        key:94,
        img:"https://m.media-amazon.com/images/I/81mw0IfvWIL._SX625_.jpg",
        name:"Mens Bumper Sneaker",
        price:"799",
        brand:"NIKE"
    },
    {
        key:95,
        img:"https://m.media-amazon.com/images/I/71xWtLhH2GL._SX625_.jpg",
        name:"Casual Shoe",
        price:"799",
        brand:"ADIDAS"
    },
    {
        key:96,
        img:"https://m.media-amazon.com/images/I/41Mvp90ah9L._SY695_.jpg",
        name:"Sneakers",
        price:"999",
        brand:"NIKE"
    },
    {
        key:97,
        img:"https://m.media-amazon.com/images/I/71k2RaCoofL._SY625_.jpg",
        name:" Casual Sneaker ",
        price:"700",
        brand:"PUMA"
    },
    {
        key:98,
        img:"https://m.media-amazon.com/images/I/61KpHOx79FL._SY625_.jpg",
        name:"Comport Sneakers",
        price:"799",
        brand:"PUMA"
    },
    {
        key:99,
        img:"https://m.media-amazon.com/images/I/71s4yJYxVjL._SY625_.jpg",
        name:"Casual Sneaker Shoes ",
        price:"2240",
        brand:"PUMA"
    },
    {
        key:100,
        img:"https://m.media-amazon.com/images/I/71lFYVmnDEL._SY625_.jpg",
        name:" Ruben Sneaker",
        price:"250",
        brand:"CROCS"
    }
    
]
export default data;